---
- name: Try different SSH configurations for a multihomed host
  tags: multihomed
  # We are forced to include a different file with tasks, instead of a block
  # because of https://stackoverflow.com/questions/58908625/issue-looping-on-block-containing-a-set-of-tasks-in-ansible.
  loop: '{{ multihomed }}'
  loop_control:
    loop_var: multihomed_entry
  include_tasks:
    file: ssh.yml
    apply:
      tags: multihomed

- name: Mark host as unreachable if no connection settings worked
  ansible.builtin.group_by:
    key: unreachable
  when: multihomed | length > 0 and multihomed_entry_result.failed | default(false)

- name: Fail for host if no connection settings worked
  ansible.builtin.fail:
      msg: No connection settings worked for this multihomed host
  when: multihomed | length > 0 and multihomed_entry_result.failed | default(false)

- name: Ignore host if no connection settings worked
  ansible.builtin.meta: end_host
  when: multihomed | length > 0 and multihomed_entry_result.failed | default(false)
