---
- name: Ensure the host is up and running
  tags: ping
  ansible.builtin.ping:

- name: Fail if hostname does not match expected value
  tags: ping
  ansible.builtin.assert:
    that: ansible_facts["hostname"] == (expected_hostname | default(inventory_hostname))
    fail_msg: 'Hostname as discovered by Ansible ({{ ansible_facts["hostname"] }}) does not match expected hostname ({{ expected_hostname | default(inventory_hostname) }})'
    success_msg: Hostname as discovered by Ansible matches expected hostname
